source 'https://api.berkshelf.com'

metadata

cookbook 'runnable_nodejs', git: 'git@github.com:CodeNow/runnable_nodejs-cookbook', tag: '0.1.4'

cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'minitest-handler', github: 'btm/minitest-handler-cookbook'
